# Generated by Django 4.2.5 on 2023-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='doctor', max_length=100),
        ),
    ]
