# Generated by Django 4.2.5 on 2023-09-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_remove_patient_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
